- ReadMe.md
Immutable was incorrectly spelled as inmmutable
> Fix spelling of immutable in README

- ReadMe.md
- ReadMe.zh-CN.md
> Fixed: readme

- ReadMe.md
- ReadMe.zh-CN.md
Hi!
This project looks very promising! 
I will definitely give it a try on my projects.
I found a small error in the `isLeapYear` docs as the function does not take any arguments.
> Fix isLeapYear docs

- ReadMe.md
> Fix typo in ReadMe.md

- src/index.js
> fix(bug): fix endOf month

- ReadMe.md
Added all of the possible display formats to the Readme documentation.
> Update format readme

- index.d.test.ts
- index.d.ts
- karma.sauce.conf.js
- package.json
- src/index.js
- test/browser.spec.js
- test/index.d.test.ts
- test/manipulate.test.js
- test/parse.test.js
> fix month parse bug without leading zero

- package.json
- src/index.js
- test/manipulate.test.js
> fix: fix add millisecond

- docs/zh-cn/I18n.md
Sorry, I forget to add same change into Chinese doc also :(
> Fix not closed bracket in Chinese doc

- docs/en/API-reference.md
Just fixed typos which I found while translating.
> Fix typo in docs

- .gitignore
- src/locale/ja.js
I added `ja` locale for Japanese.
Please review when you have time!
> Add Japanese (ja) locale

- docs/zh-cn/I18n.md
- docs/zh-cn/Plugin.md
- src/locale/ru.js
> Complete Chinese translation

- README.ja.md
- README.md
- README.zh-CN.md
- docs/ja/API-reference.md
- docs/ja/I18n.md
- docs/ja/Installation.md
- docs/ja/Plugin.md
- docs/ja/README-ja.md
Hello @iamkun 
As I promised on https://github.com/iamkun/dayjs/issues/164, I translated all documents into Japanese.
I hope those docs would help more people. 
Closes: #164
> Add Japanese documents

- docs/ja/README-ja.md
@iamkun 
Sorry, that's my bad!
> Fix broken link in README-ja

- src/locale/nl.js
> Add NL locale

- src/locale/bg.js
This PR adds a Bulgarian locale file. Would be happy to see this merged. Cheers!
> Add Bulgarian (bg) locale

- package.json
- src/locale/it.js
And the "cross-env" package for developer using windows.
> Add Italian locale

- docs/en/API-reference.md
Fixed ’Start of time’ section decription.
> Fixed typo

- src/locale/pt-br.js
We should do that with all the locales we could...
> Added relativeTime to Portuguese-br locale

- src/locale/tr.js
Add relative times to Turkish locale file
> Improve Turkish localization

- docs/en/I18n.md
Fix missing colon in locale template
> Fix missing colon in locale template

- src/locale/nl.js
Adds relativeTime translations for NL
> Add relativeTime support for NL

- src/locale/zh-tw.js
> Add Taiwan (zh-tw) locale

- src/locale/zh-cn.js
- src/locale/zh-tw.js
> fix: fix  Advanced format bug in zh-cn

- src/locale/ka.js
At ISO 639-1:2002 georgian language has `ka` code.
> Add georgian locales

- package.json
- src/plugin/isBetween/index.js
- test/plugin/isBetween.test.js
Sets testURL in jest config for resolve issue with failing tests
#287
> Implements isBetween plugin

- docs/en/API-reference.md
- docs/en/Plugin.md
- docs/ja/API-reference.md
- docs/ja/Plugin.md
- docs/ko/API-reference.md
- docs/ko/Plugin.md
- docs/pt-br/API-reference.md
- docs/pt-br/Plugin.md
- docs/zh-cn/API-reference.md
- docs/zh-cn/Plugin.md
update german locale, add romanian locale
fix #287
> fix: add isBetween API & update

- src/locale/nn.js
Adds support for Norwegian Nynorsk (`nn`).
_Not to be confused with the already existing Norwegian Bokmål (`nb`)._
> Add Norwegian Nynorsk Locale (nn)

- src/locale/pl.js
> Add Polish locale (pl)

- src/locale/nl.js
> Correct dutch translation of hours and years

- src/locale/ar.js
I'm not a all arabic, i just have a traduction file from my company.
I've also check with the momentjs locale file
Hope this can help :)
> feat: add arabic locale

- src/locale/pt.js
I'm not portuguese but I've been helped by portuguese friend and traduction file of my company
The only difference with brazilian portuguese is relativeTime.s
Hope this can help :)
> feat: add portuguese locale

- src/locale/sk.js
- fix weekdays order (!)
- slovak use lowercased month names in dates
- remove some Spanish(?) article, forgotten during translation
> Fix Slovak locale issues

- src/locale/ja.js
Added Japanese weekdaysShort and weekdaysMin
> Added Japanese weekdaysShort and weekdaysMin

- src/locale/pl.js
Polish locale needs also `weekdaysShort` and `weekdaysMin`
> add weekdaysShort and weekdaysMin to polish locale

- src/locale/fa.js
I have added relativeTime to locale object which it was missing from fa.js.
Peace! ✌🏻
> updating Farsi/Persian locale file

- docs/zh-cn/Plugin.md
> fix typo in zh-cn/Plugin.md

- docs/en/API-reference.md
> /cul fu ar

- LICENSE
> Happy new year 🎉🎉🎉

- src/index.js
> perf(format): reuse matches instead of created when replacing

- src/locale/de-at.js
This PR adds in the de-AT locale, based in the de locale, with differences in the months name and the seconds.
> Added de-AT locale

- README.md
> 修复readme118行空格115行空行

- src/locale/pt.js
Added some missing properties and localized formats
> Improved PT locale

- src/locale/ko.js
Hi, 
I add weekdays short to ko locale
> Add weekdaysShort to ko Locale

- types/index.d.ts
> fix: Fix `.diff` type definition error

- docs/ja/API-reference.md
> Add translate `weekday` to Japanese in API Reference

- docs/en/API-reference.md
- docs/ko/API-reference.md
> fix dead link in API-reference.md

- src/locale/pt-br.js
Hello ✋ 
Just adding the some properties to pt-br locale:
> Improving pt-br locale

- docs/pt-br/I18n.md
Add docs for 'weekStart' and replacing 'locale' to 'localidade' on code comments.
> Improving pt-br documentation

- src/index.js
- src/locale/pt-br.js
- test/display.test.js
fixing https://github.com/iamkun/dayjs/issues/632
> Return null in toJSON if not valid

- src/locale/ar.js
- src/locale/bg.js
- src/locale/ca.js
- src/locale/cs.js
- src/locale/de-at.js
- src/locale/de.js
- src/locale/el.js
- src/locale/fa.js
- src/locale/fr.js
- src/locale/he.js
- src/locale/hr.js
- src/locale/ka.js
- src/locale/lt.js
- src/locale/ms.js
- src/locale/ne.js
- src/locale/nl.js
- src/locale/pt-br.js
- src/locale/ro.js
- src/locale/sk.js
- src/locale/sr-cyrl.js
- src/locale/sr.js
- src/locale/tr.js
This PR adds weekdaysShort to those locale files that they do not have this variable defined.
> Add missing weekdaysShort in translation files

- src/locale/sv.js
- test/locale/sv.test.js
> fix: Update Swedish locale (sv) fix ordinal error

- src/plugin/localeData/index.js
- test/plugin/localeData.test.js
> fix: Update LocaleData plugin to support dayjs().longDateFormat()

- types/plugin/dayOfYear.d.ts
Minor bug fix. The current version doesn't handle the case where the date is being set. Thanks!
> Handle value setting in dayOfYear call signature

- src/plugin/isoWeekOfYear/index.js
- test/plugin/isoWeekOfYear.test.js
- types/plugin/isoWeekOfYear.d.ts
> add isoWeekOfYear plugin

- src/locale/fr.js
- test/plugin/localeData.test.js
Issue: https://github.com/iamkun/dayjs/issues/861
> fix(locale/fr): fix monthsShort for locale fr

- src/index.js
- src/plugin/utc/index.js
- test/plugin/utc-utcOffset.test.js
> fix: Fix UTC plugin startOf, endOf bug

- src/plugin/duration/index.js
- test/plugin/duration.test.js
- test/plugin/relativeTime.test.js
> fix: Fix Duration Plugin `.toISOString` format bug

- src/locale/tk.js
> Add Turkmen (tk) locale

- src/plugin/customParseFormat/index.js
fix https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/25
> fix: Fix CustomParseFormat plugin set locale error

- types/index.d.ts
> fix: Update type definition to support strict mode

- src/plugin/timezone/index.js
- src/utils.js
> Fix typo at timezone/index.js

- src/constant.js
- test/parse.test.js
> fix: fix parse date string error e.g. '2020/9/30'

- src/plugin/timezone/index.js
- test/plugin/timezone.test.js
> fix: Fix Timezone plugin UTCOffset rounding bug

- src/plugin/isoWeek/index.js
- test/plugin/isoWeek.test.js
> fix: fix isoWeek Plugin cal bug in UTC mode

- src/plugin/utc/index.js
- test/plugin/utc.test.js
> fix: fix UTC plugin bug while comparing an utc instance to a local one

- build/esm.js
> Added typedefs in esm build

- src/plugin/timezone/index.js
- test/plugin/timezone.test.js
Support to set default timezone.
> feat: timezone api - tz.setDefault

- .gitignore
- build/index.js
- src/locale/bi.js
- src/locale/en.js
- test/locale/keys.test.js
> build: output locale list json file

- types/plugin/timezone.d.ts
> Fix optional types for .tz()

- src/plugin/localeData/index.js
- test/plugin/localeData.test.js
> add longDateFormat to global localeData

- src/locale/ca.js
> Improve ordinal method (ca)

- types/index.d.ts
> Add descriptions to types

- src/plugin/timezone/index.js
- test/plugin/timezone.test.js
- types/plugin/timezone.d.ts
> fix: update timezone plugin to support custom parse format

- src/plugin/utc/index.js
- test/timezone.test.js
> fix: fix UTC plugin diff bug in DST

- src/plugin/localeData/index.js
- test/plugin/localeData.test.js
- types/plugin/localeData.d.ts
> fix: update localeData plugin to support meridiem

- src/plugin/customParseFormat/index.js
> fix: fix customParseFormat plugin parsing date bug

- src/plugin/utc/index.js
- test/plugin/utc.test.js
> fix: fix diff bug when UTC plugin enabled

- package.json
> feat: add ES6 Module Support, package.json module point to "esm/index.js"

- src/locale/pt.js
Updated yearStart of pt-locale to 4. 
Related to #1344
> fix: update yearStart from locale-pt

- types/plugin/duration.d.ts
See https://github.com/iamkun/dayjs/issues/1360
> fix: revert removed type definitions

- src/locale/ru.js
Fixed issue iamkun#1371
Added yearStart: 4 to https://github.com/iamkun/dayjs/blob/dev/src/locale/ru.js
> Issue #1371 fixing ru locale

- src/locale/ar-dz.js
- src/locale/ar-kw.js
- src/locale/ar-ly.js
- src/locale/ar-ma.js
- src/locale/ar-sa.js
- src/locale/ar-tn.js
Close #1282
@hazemmadkour Can you please check the code if the localization is correct?
> feat(locale): add meridiem in ar languages

- src/locale/ru.js
- test/locale/ru.test.js
- Added ru meridiem
- Added unit tests
- Using same logic as moment's [ru meridiem](https://github.com/moment/moment/blob/f5233ee5d44ba20079cd4b389262719bb20e23bd/locale/ru.js#L183-L191)
> feat: Add ru meridiem

- docs/en/Plugin.md
- types/plugin/utc.d.ts
Attemp to fix #1027 . If there are anything I need to change or make, let me know.
> Updating the docs & TS Type File to be able to use strict parsing with UTC plugin

- src/index.js
- test/plugin/updateLocale.test.js
Thought I would try my hand at it 😊
Resolves #1465
> feat: add invalid date string override (#1465)

- src/plugin/customParseFormat/index.js
- test/plugin/customParseFormat.test.js
> fix: update customParseFormat plugin strict x X parsing

- types/plugin/duration.d.ts
Fixes esm duration typing reference.
Contains the required part of https://github.com/iamkun/dayjs/pull/1544.
> Fix esm duration typings.

- types/plugin/utc.d.ts
Fixes https://github.com/iamkun/dayjs/issues/1603
> fix: changed utcOffset method typo from UTC plugin

- src/locale/es-mx.js
Adding support for es-mx locale.
#171
> Add support for es-mx locale

- docs/es-es/README-es-es.md
- docs/ja/README-ja.md
- docs/ko/README-ko.md
- docs/pt-br/README-pt-br.md
- docs/ru/README-ru.md
- docs/zh-cn/README.zh-CN.md
Changes:
- added links to readme files in different languages
- added link to [main documentation](https://day.js.org/) as is in main readme file
> add references to another readme files

- types/plugin/updateLocale.d.ts
Changes:
* fix types for updateLocation plugin
> update updateLocal to have proper TS types

- src/locale/gl.js
I've added relative time expressions to Galician language and also fixed ordinals in this language.
> Added relative time to .gl (Galician) and fixed ordinals

- docs/pt-br/README-pt-br.md
I translated the part about the documentation, which is the only thing that isn't translated yet in the README.
> Improve PT-BR translation for README-pt-br.md

- types/plugin/localeData.d.ts
This pull request add `ordianl` property in `InstanceLocaleDataReturn` and `GlobalLocaleDataReturn` types
https://github.com/iamkun/dayjs/issues/1922
> fix: add property ordinal

- README.md
- docs/si/README-si.md
**What's in this PR?**
Added sinhalese / sinhala readme for understand & read easily.
First come and first take, i like to acquire remaining space in the language line :)
Member of [@HelaBasa](https://crowdin.com/profile/helabasa) unit, Nawala.
> Add & update Sinhala README

- src/locale/ar-dz.js
- src/locale/ar-iq.js
- src/locale/ar-kw.js
- src/locale/ar-ly.js
- src/locale/ar-ma.js
- src/locale/ar-sa.js
- src/locale/ar-tn.js
- test/locale/ar-dz.test.js
- test/locale/ar-iq.test.js
- test/locale/ar-kw.test.js
- test/locale/ar-ly.test.js
- test/locale/ar-ma.test.js
- test/locale/ar-sa.test.js
- test/locale/ar-tn.test.js
> fix: ar-* meridiem function implementation is wrong

- src/plugin/isToday.ts
- tests/plugin/isToday.test.ts
- tsconfig.json
feat: add tests for plugin `isToday` to dayjs 2.0.
Unify layout of plugin code - all plugins should have the same base code structure.
Fix changes recommended by eslint.
> test: add tests for plugin isToday

- src/plugin/toArray.ts
- tests/plugin/toArray.test.ts
feat: add tests for plugin `toArray` to dayjs 2.0.
Unify layout of plugin code - all plugins should have the same base code structure.
> test: add tests for plugin toArray

- docs/es-es/README-es-es.md
- docs/he/README-he.md
- docs/ja/README-ja.md
- docs/ko/README-ko.md
- docs/pt-br/README-pt-br.md
- docs/ru/README-ru.md
- docs/si/README-si.md
- docs/tr/README-tr.md
Added Hebrew version of Readme
> Feat heb readme

- src/plugin/objectSupport/index.js
- test/plugin/objectSupport.test.js
> fix(plugin): check if null passed to objectSupport parser

- src/locale/sl.js
- test/locale/sl.test.js
Slovenian translation update so it handles dual and some plural edge cases.
> Update Slovenian translation for relative time

- README.md
- docs/es-es/README-es-es.md
- docs/he/README-he.md
- docs/ja/README-ja.md
- docs/ko/README-ko.md
- docs/pt-br/README-pt-br.md
- docs/ru/README-ru.md
- docs/si/README-si.md
- docs/tr/README-tr.md
- docs/zh-cn/README.zh-CN.md
For uniformity with other badges
> Change CI badge style

- src/locale/zh-hk.js
Contributes to #171
- add meridiem
- and update formats
- https://github.com/moment/moment/blob/develop/src/locale/zh-hk.js
- #2149
> Feat/improve locale "zh-hk"

- docs/fr/README-fr.md
Hi, here is the French translation of the README.md :)
> doc: add french README.md

- docs/sw/README-sw.md
- Added the README file with a comprehensive translation into Swahili. This update aims to provide clear project information and instructions tailored for Swahili-speaking users, ensuring accessibility and ease of understanding across diverse language communities.
> added README translation for Swahili speakers
