iamkun/dayjs

src/index.js
test/display.test.js

Added the h/hh and a/A formats.

New display formats

---

plugins/advancedFormat.js
src/index.js
test/display.test.js
test/plugin.test.js

The plugin system allows users to extend dayjs with additional plugins,
or change existing functionality.
The plugins work by calling the extend method:
```
dayjs.extend({
n: "methodName",
m: function(arguments) {
//
}
})
```
When overwriting a function, the original function can be referenced from
inside the plugin using:
```this.getOld(pluginName)```
For example:
```
dayjs.extend({
n: "format",
m: function(formatStr) {
let oldFormat = this.getOld("format")
let oldResults = oldFormat(formatStr)
...
})
```
This commit also introduces a plugin which extends the format options to include:
-Q: Quarter of the year
-k/kk: 1-24 hour time
-ddd: Date of the month with ordinal (1st-31st)
-S: Milliseconds

Added a plugin system.

---

src/index.js
test/display.test.js

This PR adds the ability to get the `diff()` of hours and minutes in addition to the types already available.
I added the two units to the test file, but this test was failing for me on master locally, so I didn't investigate too deeply as to the cause. 
Feel free to reach out if you have any concerns with this PR.

Add Hour and Minute to diff()

---

src/plugin/advancedFormat.js
test/plugin/advancedFormat.test.js

**When I run `npm run test`**：
The two letters of  an ordinal number after the number are usually **the last two letters in the word denoting that number**. So it's a bug, and I fixed it.
After fixed:

fix bug: advencedFormat plugin

---

package.json

[size-limit](https://github.com/ai/size-limit) work better with ci than `gzip-size`, and perfect for tiny module to control package size.

replace gzip-size with size-limit

---

index.d.ts

Just noticed that `toObject` return type was too generic

fixed `toObject` return type

---

index.d.ts

There is an error in the typings file with the 'locale' method of the namespace 'dayjs'
This pull request solves the problem of the name

fix 'locale' method name in index.d.ts typings file

---

src/locale/de.js

Added german relative times
```js
relativeTime: {
future: 'in %s',
past: 'vor %s',
s: 'wenige Sekunden',
m: 'eine Minute',
mm: '%d Minuten',
h: 'eine Stunde',
hh: '%d Stunden',
d: 'einen Tag',
dd: '%d Tage',
M: 'ein Monat',
MM: '%d Monate',
y: 'ein Jahr',
yy: '%d Jahre'
}
```

german relative times

---

src/locale/ja.js

Added japanese relative times.
```javascript
relativeTime: {
future: '%s後',
past: '%s前',
s: '数秒',
m: '1分',
mm: '%d分',
h: '1時間',
hh: '%d時間',
d: '1日',
dd: '%d日',
M: '1ヶ月',
MM: '%dヶ月',
y: '1年',
yy: '%d年'
}
```

japanese relative times

---

src/locale/nl.js

fix(locale-nl): set correct weekdays and months

---

src/locale/fi.js

This adds basic support for Finnish locale but atm. proper Finnish support can't be implemented until issue https://github.com/iamkun/dayjs/issues/302 is fixed.
`relativeTime` properties are now configured for past tense usage only because I think it's a more common use case with this kind of library.
For now using future tense with this locale will result in incorrect forms and text that doesn't make sense.

Add Finnish locale

---

README.md
docs/es-es/API-reference.md
docs/es-es/I18n.md
docs/es-es/Installation.md
docs/es-es/Plugin.md
docs/es-es/README-es-es.md
src/locale/es-es.js

Note: I cloned `src/locale/es.js` into `src/locale/es-es.js`,
similarly to how was done with `pt` and `pt-br`.
The reason is obvious: so many Spanish dialects. Leaving it with only
`es` would be problematic, especially when someone from another
Spanish-speaking country come to suggest editions because of this
Spanish not being the Spanish he is used to (understandable). And this is, as far as I can see,
already done and accepted with, at least, `pt`, so I think this
will be OK. Tell me if not and I will edit it
(remove it `/src/locale/es-es`, docs better have that way, so much text, could
be so different between countries) but have in mind the previous reasoning ^^.

add spanish documentation & extra locale

---

docs/en/API-reference.md
docs/es-es/API-reference.md
docs/ja/API-reference.md
docs/ko/API-reference.md
docs/pt-br/API-reference.md
docs/zh-cn/API-reference.md

```
export type UnitType = 'millisecond' | 'second' | 'minute' | 'hour' | 'day' | 'week' | 'month' | 'quarter' | 'year' | 'date'
```

Fix .diff() UnitType for Typescript.

---

docs/ko/Plugin.md
docs/ko/README-ko.md

as titled. 
- fix typo. 
- translate updated docs 
It would be great to review from @ujuc who is the origin contributor for this translation if possible! :) 
#171

translate updated docs in Korean

---

docs/ja/API-reference.md
docs/ja/Plugin.md

- translate updated docs
- change the link to Buddhist Era wikipedia to japanese wikipedia
#171

update japanese doc

---

src/locale/es-do.js
src/locale/es-us.js
src/locale/es.js
src/locale/it.js
test/locale.test.js

@anbi can you review this pr please?

fix: fix it locale error

---

index.d.ts

Thanks for this useful library!
When using Typescript, shorthand units were throwing errors because not recognized.
On a side note, I wonder if the same type (UnitType) should be used for `set()` and `add()/subtract()`methods. Because the former does not take a `week` as a unit (which would count as valid in TS typings). Just a thought.

Added shorthand units to UnitType

---

docs/en/API-reference.md
docs/es-es/API-reference.md
src/constant.js
src/index.js
test/display.test.js

I've looked into momentjs code, and tried to understand why method dayjs().diff() was returning different values than moment().diff() when the unit was day. Happens that momentjs uses the offset of each element to calculate hour zone difference, and adds it to the equation.
I've had to add the utcOffset() method in the core (where the diff() method is), but only the get version.
This should resolve #384
As mentioned at #452 I've added test and documentation for `utcOffset` method

Added deltaZone in the equation when calculating diff and added utcOffset api method

---

package.json
src/locale/en-gb.js

Added a new locale for en-gb that supports the time and date formats.

Added en-gb-locale

---

src/locale/fi.js
src/locale/sv.js

Swedish locale was missing weekdaysShort and Min, and monthsShort.
Finnish locale's monthsShort was same as months. It is now updated to be similar to moment.

Update Swedish and Finnish locales

---

.gitignore
src/locale/fa.js

Word orders in relativeTime object has been corrected for locale 'fa'.

Word orders corrections for locale 'fa'

---

index.d.ts

fix d.ts file for #74 
https://github.com/iamkun/dayjs/blob/56050c2c97d8c5b2c0990b6b910b0d190fbb8d44/src/index.js#L318
https://github.com/iamkun/dayjs/blob/56050c2c97d8c5b2c0990b6b910b0d190fbb8d44/src/index.js#L98-L109

fix: fix declaration file

---

src/index.js
test/parse.test.js

Refactor parseDate

---

docs/en/API-reference.md

The current behavior is treat curly brackets as regular characters, only the square brackets have special behavior.
Related code:
https://github.com/iamkun/dayjs/blob/8ede9b76974a1aa7a14f144c58c5e4ce63c393d6/src/index.js#L304-L307
https://github.com/iamkun/dayjs/blob/8ede9b76974a1aa7a14f144c58c5e4ce63c393d6/src/constant.js#L30

Fix docs about escaping with curly brackets

---

package.json
src/index.js
src/plugin/advancedFormat/index.js
src/plugin/buddhistEra/index.js
src/plugin/customParseFormat/index.js
src/plugin/utc/index.js
src/utils.js
test/plugin.test.js
test/plugin/utc.test.js
test/utils.test.js
types/index.d.ts
types/plugin/utc.d.ts

fix: Add UTC mode with UTC plugin

---

src/locale/az.js

Create az.js, add locale support for Azerbaijani language(az)

add locale support for Azerbaijani language(az)

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

Fixed issue #533 
Got Invalid Date when use customParseFormat parse.

fixed formatting issue

---

docs/en/I18n.md
docs/en/Plugin.md
docs/pt-br/I18n.md
src/constant.js
src/index.js
src/locale/ca.js
src/locale/cs.js
src/locale/fi.js
src/locale/he.js
src/locale/ja.js
src/locale/ko.js
src/locale/lt.js
src/locale/sv.js
src/locale/zh-cn.js
src/locale/zh-tw.js
src/plugin/localizedFormat/index.js
test/display.test.js
test/locale/keys.test.js
test/parse.test.js
test/plugin/localizableFormat.test.js

This PR tries to bridge the gap between dayjs and moment by implementing lowecase/short localizable formats, already present in moment, since 2.0.0

feat: add support for lowercase localizable formats (l, ll, lll, llll)

---

src/plugin/calendar/index.js
test/plugin/calendar.test.js

in order to use global config, no need set the date format in every point

:sparkles: support set global config for calendar in locale file

---

docs/en/API-reference.md
docs/es-es/API-reference.md
docs/pt-br/API-reference.md

Just noticed this tiny typo in your docs!

Typo fix in API-reference.md

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

fixed parsing issue

---

src/locale/id.js

Add Monthshort, Dayshort to support locale Indonesian.

Add: Monthshort, Dayshort to support locale Indonesian

---

docs/en/I18n.md
docs/es-es/I18n.md
docs/ja/I18n.md
docs/ko/I18n.md
docs/pt-br/I18n.md
docs/zh-cn/I18n.md
src/index.js
src/locale/ja.js
test/display.test.js
test/locale/keys.test.js

fix: Allow customizing "am" / "pm" strings with locale meridiem function

---

src/plugin/advancedFormat/index.js
src/plugin/buddhistEra/index.js
test/plugin/advancedFormat.test.js
test/plugin/buddhistEra.test.js

fix: skip interpolation for strings inside square brackets

---

src/index.js
src/locale/ru.js
test/display.test.js
test/locale/keys.test.js
test/locale/ru.test.js

fix: Update locale month to support both array and function

---

src/plugin/relativeTime/index.js
test/plugin/relativeTime.test.js

Fix error in relativeTime plugin when the interval is 1 second

---

types/plugin/quarterOfYear.d.ts

Make `isSame` accept `quarter` as unit

TypeScript Definition: Make `isSame` accept `quarter` as unit with `quarterOfYear` imported

---

src/plugin/quarterOfYear/index.js
test/plugin/quarterOfYear.test.js

fix: Fix QuarterOfYear plugin bug

---

package.json
src/index.js
test/display.test.js
test/timezone.test.js

fix: Fix UTC plugin add day DST bug

---

src/index.js
src/plugin/localeData/index.js
test/locale.test.js
test/plugin/localeData.test.js

fix: Fix dayjs.locale() returns current global locale

---

src/locale/fr.js

French months are lowercase (unless beginning a sentence). This brings `fr` locale in line with `fr-ca` and `fr-ch`.

Lowercase french locale months+weekdays

---

types/index.d.ts

If passing only one argument to a dayjs diff method, it is said that the type is not correct.
So I fixed it.
-  document
- code

modify types of diff

---

src/locale/da.js

This PR adds the optional properties `weekdaysShort`, `weekdaysMin` and `monthsShort` to the Danish locale.
All changes have been crosschecked using a Danish dictionary:
https://ordnet.dk/ddo/ordbog

Add optional properties to DA locale

---

src/locale/ko.js

Hey, at the first, thank you for great and modern date library! 
This PR is really simple - just adding meridiem locale for 'ko'.
Korean has its unique meridiem notation '오전'(AM) and '오후'(PM) but dayjs doesn't provide it yet so I add it!
Have a nice day.

fix: add meridiem locale for ko

---

src/plugin/weekOfYear/index.js
test/plugin/weekOfYear.test.js

Handle locale in weekOfYear plugin
close #650

Fixes issue#650

---

src/locale/nb.js

"for %s siden" is a double meaning, "for" means "for" and "siden" means since. The translation here is basically `for %s since`.
In Norwegian it works, and it's a common way to communicate verbally, but in writing it becomes redundant. I've also read that you like to keep these things similar to Moment, which is what I'm switching from, and I reacted on this immediately :/
As a side note, the language name here should be `nb_NO` or from what I can gather from your structure `no-nb`. Norway has two official languages, that being `nb_NO` and `nn_NO`

Fix double meaning for nb locale

---

src/locale/uk.js

relativeTime.past is defined as '%s назад' which is Russian translation. Correct Ukrainian localisation is '%s тому'.

Minor localisation change

---

.gitignore
types/index.d.ts
types/locale/index.d.ts
types/locale/types.d.ts

@iamkun This PR improves locale user experience for TypeScript users, please help to review.

feat(ts): add missing locale type definitions

---

src/locale/bi.js

Bislama is the national language of Vanuatu. 
Perhaps there may be a rule about `weekdaysMin` being 2 characters but I needed 3 characters for Sunday/Saturday. Same for my choice of using a 4 character `weekdaysShort` for Friday. The `ae` in `Fraede` is a diphthong and would be wrong I believe if the vowels are not kept together.

Add Bislama Locale

---

src/locale/et.js
test/locale/et.test.js

Since https://github.com/iamkun/dayjs/pull/767 got merged, I added correct future tense for Estonian locale.

feat: Add correct Estonian relativeTime locale for past and future tense

---

src/locale/fi.js
test/locale/fi.test.js

This fixes problems in Finnish translation (#351) which are now possible to solve after merging #767. Also, the output is now the same as in Moment.js.

fix: Relative times in Finnish locale

---

types/plugin/isoWeek.d.ts

Fix isoWeek plugin typescript definition.
https://github.com/iamkun/dayjs/issues/827
fix: #827

Fix isoWeek plugin typescript definition #827

---

src/locale/zh.js
test/locale/zh.test.js

In `window.navigator.languages` in Chrome, there are 4 valid Chinese locales that could appear: `zh`, `zh-cn`, `zh-cn`, `zh-hk`. Currently `zh` is missing from dayjs. This PR adds the `zh` locale.
`zh` has some minor improvements over the other 3 locales. For developers, this won't affect your existing code, but if you start using `zh`, your output will be slightly more correct in some occasional cases.
For example:
```js
// no more unecessary whitespace:
dayjs().locale('zh-cn').subtract(7, 'month').fromNow() // 7 个月前
dayjs().locale('zh').subtract(7, 'month').fromNow() // 7个月前
// use "后" instead of "内" for relative future:
dayjs().locale('zh-cn').add(3, 'day').fromNow() // 3 天内
dayjs().locale('zh').add(3, 'day').fromNow() // 3天后
// improve ordinal week of year: …
```

add zh locale

---

src/locale/cs.js
src/locale/sk.js
test/locale/sk.test.js

- Add functions to generate correct noun for time periods (based on `cs.js`);
- Add `sk.test.js` (based on `cs.test.js`);
- Fix a comment in `cs.test.js`.

Fix `sk.js` (fixes #831)

---

src/plugin/calendar/index.js
test/plugin/calendar.test.js

This PR resolves issue #806 
Now the second param of `dayjs().calendar(...)` can be an object of callbacks, and the old behavior with a simples object of strings is working too!
I added some tests too for test this new feature. Hope that helps!

Add option callback to calendar plugin

---

src/plugin/relativeTime/index.js
src/utils.js
test/plugin/relativeTime.test.js
types/index.d.ts
types/plugin/relativeTime.d.ts

feat: add strict and custom thresholds support for relativeTime plugin

---

src/plugin/isToday/index.js
src/plugin/isTomorrow/index.js
src/plugin/isYesterday/index.js
test/plugin/isToday.test.js
test/plugin/isTomorrow.test.js
test/plugin/isYesterday.test.js
types/plugin/isToday.d.ts
types/plugin/isTomorrow.d.ts
types/plugin/isYesterday.d.ts

As requested for #299. But I don't know what I should do with 7e2dcc0. @iamkun what do you think? May be just drop it from my branch?
close #299

isToday, isTomorrow, isYesterday plugins

---

src/locale/br.js

eur e brezhoneg Lizherennañ
Mat eo g.m. evit PM (goude merenn) ha a.m. evit AM (a-raok merenn).
--
Should be g.m. for PM, stand for goude merenn and a.m. for AM stand for a-raok Merenn
Here some sources :
http://www.brezhoneg.bzh/177-divizou-hag-erbedadennou-ar-chuzul-skiantel.htm
https://www.unicode.org/cldr/charts/latest/summary/br.html

[locale] Breton [br]: Fix lack of meridiem

---

types/index.d.ts

the first parameter of locale is optional so that locale() can be called with no arguments to return the current locale.
I would have added a test case to prove this works, but everything is in javascript and I expect you would not appreciate adding typescript to the unit tests.
This fixes #870

fixed incorrect definition of locale in typescript

---

src/plugin/duration/index.js
test/plugin/duration.test.js

fix #865
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

fix: Fix Duration plugin get seconds

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

fix: Fix CustomParseFormat plugin of parsing only YYYY / YYYY-MM bug

---

src/plugin/relativeTime/index.js

if require('dayjs/locale/en')
instance.$locale().relativeTime is undefined
Loc in fromTo is undefined
The loc[t.l] throws an error: Cannot read property 'xx' of undefined

Fix: Update RelativeTime plugin default config

---

src/plugin/weekOfYear/index.js
test/plugin/badMutable.test.js

fix https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/22

fix: Fix WeekOfYear plugin bug while using BadMutable plugin

---

src/index.js
src/plugin/customParseFormat/index.js
src/plugin/utc/index.js
test/plugin/customParseFormat.test.js
test/plugin/isoWeek.test.js

fix: Update CustomParseFormat plugin strict mode

---

src/plugin/objectSupport/index.js
test/plugin/objectSupport.test.js
test/plugin/relativeTime.test.js
types/plugin/objectSupport.d.ts

add/set/subtract support Object parameter
and constructor support Object parameter
The related unit tests have been added.

feat:add plugin objectSupport

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

Add formats Array support `dayjs('2020-02-02', ['YYYY', 'YYYY-DD-MM'])`
#817

fix: Update CustomParseFormat plugin to support Array formats

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

fix: Fix CustomParseFormat plugin month index error

---

src/plugin/localeData/index.js
test/plugin/localeData.test.js

fix: LocaleData plugin supports locale order

---

types/index.d.ts

fix: Update type definition to support array format

---

src/plugin/duration/index.js
test/plugin/duration.test.js

fix: Duration plugin supports parse ISO string with week (W)

---

src/locale/es-pr.js
src/locale/ht.js

I would like to add localization/ support for Haitian Creole (ht) and Spanish (Puerto Rico) (es-PR).
Please let me know if I need to do something more on this branch.
Thank you. :) 
_Note: The Haitian Creole translation was contributed by Steve Patrick Louis_

Adding localization for Haitian Creole and Spanish (Puerto Rico)

---

src/index.js
test/plugin/utc-utcOffset.test.js

fix: add month or year changes hour when utc offset is used

---

src/constant.js
src/index.js
test/plugin/utc.test.js

When only 'YYYY', parsed result was incorrect.
```bash
TZ=Asia/Tokyo yarn jest ./test/parse.test.js
```
Output:
```
● Parse › moment-js like formatted dates
expect(received).toBe(expected) // Object.is equality
Expected value to be:
"2018-01-01T00:00:00+09:00"
Received:
"2018-01-01T09:00:00+09:00"
37 |     expect(dayjs(d).valueOf()).toBe(moment(d).valueOf()) // not recommend
38 |     d = '2018'
> 39 |     expect(dayjs(d).format()).toBe(moment(d).format()) // not recommend
40 |     d = '2018-05-02T11:12:13Z' // should go direct to new Date() rather our regex
41 |     expect(dayjs(d).format()).toBe(moment(d).format()) // not recommend
42 |   })
at Object.<anonymous> (test/parse.test.js:39:31)
```
Failed this test in my local env which is in `Asia/tokyo` time zone.
Compare dayjs and moment: …

Parse 'YYYY' correctly

---

src/plugin/utc/index.js
test/plugin/utc-utcOffset.test.js
types/plugin/utc.d.ts

fix: update UTC plugin to support keepLocalTime

---

src/locale/pt-br.js

In Brazil the first day of the week is Sunday, not Monday.

Update weekStart for pt-br

---

src/plugin/timezone/index.js
test/plugin/timezone.test.js
types/plugin/timezone.d.ts

fix: fix Timezone plugin parsing js date, Day.js object, timestamp bug

---

src/plugin/pluralGetSet/index.js
test/plugin/pluralGetSet.test.js
types/plugin/pluralGetSet.d.ts

feat: adds plugin for plural getters/setters

---

src/plugin/timezone/index.js
test/plugin/timezone.test.js

fix: fix Timezone plugin to preserve milliseconds while changing timezone

---

src/constant.js
src/index.js
test/parse.test.js
test/plugin/utc.test.js

fix #544
support parsing 
```
dayjs('2019-03-25T06:41:00.999999999')
```

fix: support parsing unlimited decimals of millisecond

---

src/plugin/duration/index.js
test/plugin/duration.test.js

fix #1007
this will support set duration plugin global locale
```
dayjs.locale('zh-cn')
dayjs.duration(24 * 60 * 60 * 1000).humanize() // in zh-cn locale
```

fix: update Duration plugin to support global locale

---

src/utils.js
test/plugin/badMutable.test.js

fix: fix BadMutable plugin bug in .diff

---

types/plugin/duration.d.ts

export Duration type for typescript project to use

fix: export Duration type in duration plugin

---

src/locale/hr.js
src/locale/lt.js
src/locale/pl.js
test/locale/hr.test.js
test/locale/lt.test.js
test/locale/pl.test.js

Fixing months names for Polish, Hungarian and Lithuanian locales:
- added formatted month names
- added function which determines which format to use
Fixing weekday names casing.
#1044

Fix Polish, Hungarian and Lithuanian localization.

---

src/locale/am.js

Amharic is the most used official working language of Ethiopia.
This PR adds support for Amharic locale.
_**Note**: The days and months in this locale are the direct English terms to Amharic translations of the Gregorian Calendar, and not the actual terms used in the locally unique [Ethiopian Calendar](https://en.wikipedia.org/wiki/Ethiopian_calendar) system._

Add Amharic locale

---

src/locale/fi.js

For some reason days ended with the letter "o" instead of dots, so "15o [month]".
This is incorrect.
Source: I'm a native speaker and https://www.kielikello.fi/-/miten-paivamaara-merkitaan-

Fix finnish localization

---

types/plugin/timezone.d.ts

Timezone plugin set default timezone at v1.8.36, however `timezone.d.ts` does not have type definition of `setDefault` method.

fix: Add `setDefault` typing to timezone.d.ts

---

src/plugin/timezone/index.js
test/plugin/timezone.test.js

Fixes https://github.com/iamkun/dayjs/issues/1072

Fix timezone conversion

---

src/plugin/timezone/index.js

**Description**
Improve the parse speed of `dayjs#tz()` (the timezone plugin) by caching the result from `Intl#getDateTimeFormat()`, as it is _very slow_.
There is also a discussion on speed on Luxon's GitHub. See https://github.com/moment/luxon/issues/89#issuecomment-378826414 for a similar result by not invoking the functions in `Intl.*` more times than needed.
**Speed test**
Running the following benchmark before and after the patch.
```
suite.add('dayjs#tz', function () {
dayjs.tz("2018-06-23T23:43:12.337+08:00", "Europe/London")
})
```
Here are the results on my machine (a **~8.6x improvement**):
```
Before: dayjs#tz x 3,514 ops/sec ±2.33% (86 runs sampled)
After:  dayjs#tz x 30,347 ops/sec ±1.12% (89 runs sampled)
```

Speed up dayjs#tz()

---

src/plugin/utc/index.js
test/plugin/utc.test.js
types/plugin/utc.d.ts

fix: update utc plugin to support keepLocalTime `.utc(true)`

---

src/plugin/objectSupport/index.js
test/plugin/objectSupport.test.js

`dayjs({month: 1})` should return `2020-02-01` instead if `1970-01-01`
1. if no year provide, use the current year
2. month should be 0-based

fix: fix objectSupport plugin to get the correct result (zero-based month)

---

types/plugin/duration.d.ts

All plugins have the following format, but only the duration plugin is `export default` in types
https://github.com/iamkun/dayjs/blob/f95ac15a4577ae5a3d1ce353872a2cd9fc454bc2/src/plugin/isMoment/index.js#L1
https://github.com/iamkun/dayjs/blob/f95ac15a4577ae5a3d1ce353872a2cd9fc454bc2/types/plugin/isMoment.d.ts#L4
When dayjs is actually built, it doesn't export the `default` object, so typescript runtime error occurs on `duration.default`.
https://cdn.jsdelivr.net/npm/dayjs@1.9.1/plugin/duration.js
This is a fix that keeps the same exports as other plugins.

fix: export type of duration plugin

---

src/plugin/duration/index.js
test/plugin/duration.test.js

Fixes #1093
Now, once you've added the `Duration` plugin, you can 
```js
const d = dayjs('2020-10-01');
const days = dayjs.duration(2, 'days');
d.add(days).format('YYYY-MM-DD')); // 2020-10-03
```

Allows to add durations to dayjs instance

---

src/plugin/objectSupport/index.js
test/plugin/objectSupport.test.js

fix: fix objectSupport plugin bug in utc

---

src/locale/de.js
test/locale/de.test.js

I've fixed the relativeTime output for the 'de'-locale when withoutSuffix is set. Also added a unit-test that checks the results in absolute and against moment.

fix: de-locale for relativeTime, and added unit-tests

---

src/plugin/localeData/index.js
src/plugin/localizedFormat/index.js
src/plugin/localizedFormat/utils.js

fix: fix localizedFormat export error

---

src/plugin/duration/index.js
test/plugin/duration.test.js
types/index.d.ts
types/plugin/duration.d.ts

In #1099 support was added for passing in a duration object to `add()` or `subtract()`, which is awesome. I ran across a few issues when using it. This PR:
- adds support for `subtract(duration)` (changelog thinks this was part of #1099, but it wasn't)
- adds typescript type signatures for `add(duration)` and `subtract(duration)`
Also missing are docs for this feature, though that looks like that should be done in the [website repo](https://github.com/dayjs/dayjs-website) so not included in this PR.
Thanks a ton for dayjs!

Fix issues with adding/subtracting durations from Dayjs objects

---

src/plugin/timezone/index.js
test/plugin/timezone.test.js
types/plugin/timezone.d.ts

fix: update timezone plugin to support keepLocalTime

---

src/plugin/minMax/index.js
test/plugin/minMax.test.js
types/plugin/timezone.d.ts

fix: fix minMax plugin parsing empty array bug

---

src/index.js
src/plugin/customParseFormat/index.js
src/plugin/devHelper/index.js
types/plugin/devHelper.d.ts

fix: add devHelper plugin

---

src/index.js

Hello,
In the constructor of the Dayjs class, I changed the line:
`this.$L = this.$L || parseLocale(cfg.locale, null, true)` to
`    this.$L = parseLocale(cfg.locale, null, true)`
because `this.$L` is undefined at the time of assignment and the right operand of the OR-operation will then always set `this.$L`.
Hope it can save you some bytes!
Kind regards,
Florian

Update index.js: Changed assignment of "this.$L" in "Dayjs" constructor

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

fix: fix customParseFormat plugin parse meridiem bug

---

README.md

travis-ci.org will be closed down completely on December 31st, 2020 https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

dox: fix travis-ci build link

---

types/plugin/isoWeek.d.ts

Currently isoWeek plugin is excluding `week` from its units because it's extending from `UnitType` instead of `OpUnitType`. This raises typescript errors if the unit is of type `"isoWeek" | "week"` 
```ts
const weekFormat = foo ? 'isoWeek' : 'week';
const weekStart = date.startOf('month').startOf(weekFormat);
```
```
[tsserver 2769] [E] No overload matches this call.
Overload 1 of 2, '(unit: ISOUnitType): Dayjs', gave the following error.
Argument of type '"isoWeek" | "week"' is not assignable to parameter of type 'ISOUnitType'.
Type '"week"' is not assignable to type 'ISOUnitType'.
Overload 2 of 2, '(unit: OpUnitType): Dayjs', gave the following error.
Argument of type '"isoWeek" | "week"' is not assignable to parameter of type 'OpUnitType'.
Type '"isoWeek"' is not assignable to type …
```

fix: isoWeek plugin type

---

src/locale/lv.js

Latvian language is missing `relativeTimes` translation object so here you go :)

Add relative times to lv (Latvian) locale

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

fix: update customParseFormat plugin to parse 2-digit offset

---

src/locale/lv.js
src/plugin/relativeTime/index.js
test/plugin/relativeTime.test.js

fix: Add function handling for relativeTime.future and relativeTime.past

---

types/plugin/timezone.d.ts

The `offsetName` method for the timezone plugin was added in 1.9.0, but it's not in the TypeScript definitions.  This adds it.

Add type definition for offsetName

---

src/constant.js
src/locale/lv.js
src/plugin/duration/index.js
test/plugin/duration.test.js
types/plugin/duration.d.ts

Heya! This should close #965. Key things to note:
* Is it okay to change REGEX_FORMAT to accept singular Ys? From what I've seen in the code in `src/index.js`, it seems like the original .format() ignores regex matches which are not in the `const matches = { ... }` variable, so this should be safe to do.
* Single Y would be very useful, because you don't often display durations which has double-digit years. So you can do `dayjs.duration(15, 'years').format('Y years has passed') === '15 years has passed'`
Also, difference between the original `dayjs.format()` and this format:
* No 'A'/'a' token (because you can't reason about meridians in durations)
* No 'dddd' token
* No 'ZZ' token
Not sure why commit 6545739 got dragged along as a change in the diff, but doesn't seem like any files are …

feat: #965 add duration.format()

---

src/plugin/timezone/index.js
test/plugin/timezone.test.js
test/timezone.test.js

This fixes #1212.  Because the timezone plugin stores a `$d` value that's relative to the timezone of the dayjs instance, `startOf` and `endOf` need to ignore the absolute `$d` value and instead use the logical value in that time zone.
This overrides `startOf` to ignore the timezone of the instance, calculate the `startOf` value, then reapply the timezone while keeping local time.  This should also fix the behavior for `endOf` since it is actually calling `startOf` internally.

Fix startOf/endOf behavior with timezone

---

src/locale/he.js
test/locale/he.test.js

fix: update he locale for double units

---

types/index.d.ts

This PR adds plural form support such as
```typescript
dayjs().subtract(2, 'days')
```
in TypeScript. This is already supported in JS.

fix: add type support for plural forms of units

---

src/locale/ar.js
src/plugin/preParsePostFormat/index.js
src/plugin/relativeTime/index.js
test/locale/ar.test.js
test/plugin/preParsePostFormat.test.js
types/plugin/preParsePostFormat.d.ts

Added a plugin to implement the preparse / postformat functions for locales such as "ar", based on the moment implementation. I added tests for both the plugin and the locale changes based on the moment tests.
This should solve #416 
Do note that the relative time implementation for the ar locale does not match the moment one, so the tests for the locale are different (to focus on coverage and not correctness tests - since I am not an arabic speaker and could not fix the relative time implementation in the scope of this change).

Preparse postformat + implementation in ar locale + tests

---

src/plugin/localeData/index.js
test/plugin/localeData.test.js

Moment.js exposes the ordinal function in [localeData][1].
Let's add ordinal to the localeData plugin as well.
[1]: https://momentjs.com/docs/#/i18n/locale-data/

feat: add ordinal to localeData plugin

---

src/constant.js
test/parse.test.js

To be sure the last digit token in REGEX_PARSE only matches for milliseconds, the period must be escaped. Otherwise, it acts as a wildcard.
All of these are the same date/time using different ISO 8601 time zone formats:
`dayjs("2020-12-31T18:00:00.000-0500")`
`dayjs("2020-12-31T18:00:00-05:00")`
`dayjs("2020-12-31T18:00:00-0500")`
The first two parse correctly because REGEX_PARSE doesn't match. But the last example does match REGEX_PARSE, with the final `-` character matching the wildcard. So the date is parsed in local time and the first three characters of 0500 become 50ms.

fix: escape last period to match only milliseconds (#1239)

---

types/index.d.ts

fix: fix typescript type error UnitTypeLongPlural

---

src/constant.js
test/parse.test.js

fix: fix parse regex bug

---

package.json

ref #1281 
This change in 1.10.1 add ES6 Module Support, package.json module point to "esm/index.js" (#1298) (f63375d)
really has an unexpected breaking change, and that's of course not what we want.
I am planning to revert this change in the next release 1.10.2 and delete the "module" entry.
Besides, maybe there's no need for Day.js to support ESM bundle, this would only introduce some conflict but no benefits in the tree shaking. A better way might be a separate npm package (like "dayjs-esm") to ship an ESM package.

fix: remove module entry in package.json

---

src/plugin/devHelper/index.js
test/plugin/devHelper.test.js

fix: update devHelper add warning "passing Year as a Number will be parsed as a Unix timestamp"

---

src/locale/en-gb.js
src/plugin/weekYear/index.js
test/plugin/weekYear.test.js

fix: fix weekYear plugin missing locale bug

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

fix: fix customParseFormat plugin strict mode parse meridiem bug

---

docs/en/Plugin.md
docs/es-es/Plugin.md
docs/ja/Plugin.md
docs/ko/Plugin.md
docs/pt-br/Plugin.md
docs/zh-cn/Plugin.md
src/plugin/advancedFormat/index.js
test/plugin/advancedFormat.test.js

Like moment.js - day.js should allow the format function to be compatible with iso weeks. and since isoweeks are a plugin already, we can just call it.
Input | Example | Description
-- | -- | --
gggg | 2014 | Locale week year
w ww | 1..53 | Locale week of year
GGGG | 2014 | ISO week year
W WW | 1..53 | ISO week of year

fix: Add format options for iso week and weekyear

---

src/locale/bn.js
test/locale/bn.test.js

Following the work that has been done for AR numerals, this PR is about to add BN numeral.]
(It also fixes an inconsistency of the months with momentjs.)

Add Bengali (bn) support for numerals

---

test/plugin/duration.test.js
types/index.d.ts
types/plugin/duration.d.ts

This PR improves [Duration plugin](https://day.js.org/docs/en/durations/durations) types.
- Autocomplete:
- And for more strict checks (just compare):
```ts
// That's how computed type looks like
type plugin.DurationUnitsObjectType = {
milliseconds?: number;
seconds?: number;
minutes?: number;
hours?: number;
days?: number;
months?: number;
years?: number;
weeks?: number;
}
```
I also added `CreateDurationType` to reduce code duplication, so `duration()`, `duration.add()` and `duration.substract()` using the same function signature.
Other changes you can view in diff. Please, let me know if don't understand something. I can explain every line of code.
UPD: With this PR TypeScript users **can't** use functions `duration()`, `duration.add()` and `duration.substract()` without args any more. …

fix: Significantly improve `Duration` types

---

src/plugin/duration/index.js
test/plugin/duration.test.js

When I create Duration with negative number, the default value of each unit is -1 since you round everything down (Math.floor).
I add if case when number is negative it should run Math.ceil() instead.
For positive number
```js
const duration = dayjs.duration(1, "milliseconds")
console.log(duration) // { year: 0, month: 0, day: 0, hour: 0, minute: 0, second: 0, millisecond: 1 }
```
For negative number (current)
```js
const duration = dayjs.duration(-1, "milliseconds")
console.log(duration) // { year: -1, month: -1, day: -1, hour: -1, minute: -1, second: -1, millisecond: -1 }
```
For negative number (expected)
```js
const duration = dayjs.duration(-1, "milliseconds")
console.log(duration) // { year: 0, month: 0, day: 0, hour: 0, minute: 0, second: 0, millisecond: -1 }
```

Fix negative duration

---

src/locale/pl.js

This pull request fixes issue with weekOfYear showing wrong calendar week at the turn of the year.
Eg. the 2021-01-21 should be calendar week 3 but it shows as calendar week 4.
(similar issues: #760 #1264)
Calendar weeks:
http://www.whatweekisit.org/

fix: update Polish [pl] locale yearStart

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

This is a small fix to parse a string for MMM month format with underscore delimiters.
Was added support for next custom formats:
```js
dayjs('21_Dec_2021', 'DD_MMM_YYYY').isValid() // true
dayjs('21_Jan_2021_123523', 'DD_MMM_YYYY_hhmmss').isValid() // true
```

customParseFormat: parse a string with underscore delimiter

---

types/plugin/duration.d.ts

fix: hotfix for `Duration` types

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

Added Zulu support to customParseFormat

---

src/locale/fi.js

The Finnish locale should have 2020-12-31 as week 53. According to https://en.wikipedia.org/wiki/Date_and_time_notation_in_Finland
"The week begins with a Monday and week 1 is the week containing the year's first Thursday"

 fix: update Finnish [fi] locale yearStart config

---

src/locale/sv.js

Sweden uses ISO 8061 weeks, i.e. they follow the convention that the week that contains Jan 4th is the first week of the year.
Followed the example of #1378

Set Swedish [sv] locale to use ISO 8061 weeks

---

src/locale/sl.js

This implements Slovenian ordinals.
The language has genders and cases, but in short form just adding a dot at the end is how it's typically done, and really the only option here.

fix: Add ordinal support for Slovenian [sl]

---

src/plugin/duration/index.js

Fixes #1389 
I based on `parseFromMilliseconds` function.
I noticed there are already two failing tests:
```
● Convert › convert to target time
expect(received).toBe(expected) // Object.is equality
Expected value to be:
1401624000000
Received:
1401620400000
```

Change string to number in duration object

---

src/plugin/duration/index.js
test/plugin/duration.test.js

As described in #1398 , this PR add support to call `dayjs.duration()` to create a duration of `0`. This mimic the behavior of `Moment.JS` and ease the migration for users.

feat: add no-argument duration support

---

src/constant.js
src/plugin/utc/index.js
test/plugin/utc.test.js

✅ Closes: #1085 
* Extend `utcOffset` method with support for string argument representing the offset.
* Provide the unit test(s) for the code change.
Allow UTC offset to be defined as a string. Valid formats are:
* +HH:mm,
* -HH:mm,
* +HHmm
* -HHmm
Example usage:
```javascript
dayjs().utcOffset(`+08:00`, true)
```
After the change I ensured that:
* all tests are passing, by running `npm run test && npm run test-tz`,
* formating / code style is consistent, by running `npm run lint`*.
*There are 2 failing unit tests present on the `dev` branch and as such are present in this fix as well, however they are *not* affected by this issue / code introduced.*

[Feauture] Support string arguments to `utcOffset` method

---

types/index.d.ts
types/plugin/arraySupport.d.ts

I've added an interface called `ConfigTypeMap`, so other plugins could add their own types to `ConfigType`. The same fix could be applied to ObjectSupport in a future pull request.
Fixes #1170

fix: fixed missing types for ArraySupport plugin

---

src/locale/es-do.js
src/locale/es-pr.js
src/locale/es-us.js
src/locale/es.js
test/locale.test.js

fix: change spanish month names to lowercase

---

build/index.js
build/rollup.config.js
package.json
src/constant.js
src/plugin/utc/index.js

I was playing around with using dayjs from the `dev` branch with #1450 and Node.JS, and I noticed that the `dayjs/plugin/utc` was broken, as the plugin was instead exported under the `default` key.
```console
> const dayjs = require("."); const utc = require("./plugin/utc"); dayjs.extend(utc);
Uncaught TypeError: t is not a function
at Function.v.extend (/tmp/dayjs/dayjs.min.js:1:6319)
> console.log(utc);
{
REGEX_VALID_OFFSET_FORMAT: /[+-]\d\d(?::?\d\d)?/g,
REGEX_OFFSET_HOURS_MINUTES_FORMAT: /([+-]|\d\d)/g,
default: [Function]
}
```
It looks like Rollup does not like mixing together named exports and default exports: <https://rollupjs.org/guide/en/#default-export>
I updated Rollup to the latest version, which fixed an error with running `npm install --dev` on NPM@v7, and also added the …

Fix broken UTC plugin due to rollup

---

src/plugin/dayOfYear/index.js
test/plugin/badMutable.test.js

Fixes https://github.com/iamkun/dayjs/issues/1407
Very similar to a previous fix for WeekOfYear: https://github.com/iamkun/dayjs/pull/884
To reproduce:
```
var badMutable = require('dayjs/plugin/badMutable');
var dayOfYear = require('dayjs/plugin/dayOfYear');
dayjs.extend(badMutable);
dayjs.extend(dayOfYear);
dayjs('02.25.2020').dayOfYear(); // Should return 56, but returns 1 instead
```

fix: Fix DayOfYear plugin when using BadMutable plugin

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js
types/plugin/customParseFormat.d.ts

As proposed in #1418, with this PR a custom two-digit year parse function can be configured in the `customParseFormat` plugin

feat: support custom two-digit year parse function

---

types/index.d.ts

dayjs.diff() calculates the diff to current time.

Document argumentless diff

---

types/plugin/isBetween.d.ts

change parameter type of plugin `isBetween`

fix: parameter type

---

src/locale/sv-fi.js
test/locale/sv-fi.test.js

Swedish is an official language in Finland. They expect Swedish translations of months and days and Finnish formats

Finland Swedish locale

---

src/constant.js
test/parse.test.js

fix: more strict delimiter in REGEX_PARSE

---

test/parse.test.js
types/index.d.ts
types/plugin/isBetween.d.ts

- #1558
- fix dayjs ConfigTypeMap for Typescript
- add test case in `parse.test.ts`

fix: dayjs ConfigTypeMap

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

fix: customParseFormat support parsing X x timestamp

---

types/index.d.ts

Hi. Dayjs is a super flexible library. I love working with it, writing plugins, and contributing to it. We can change anything with plugins but the typing part does not come along well enough. ``Using interface and not using type aliases`` will improve typing for plugin authors so much better. I changed one of the more important ones in this PR.
```
dayjs(new Date(), { multipleLocales: [] })
```
or any other example. the point is more flexibility in typing for plugin authors. 
**if there is a way to solve this problem currently or any planning for changing the whole typing system(v2 doesn't hit that), let me know <333**

Add format object type to index.d.ts

---

types/index.d.ts

fix: narrow type for `add` and `subtract`

---

README.md
docs/es-es/README-es-es.md
docs/ja/README-ja.md
docs/ko/README-ko.md
docs/pt-br/README-pt-br.md
docs/ru/README-ru.md
docs/zh-cn/README.zh-CN.md

This PR modified the url of `img.badgesize.io` to `https` protocol to avoid camo proxying used by github.
View details about [Proxying User Images](https://github.blog/2014-01-28-proxying-user-images).

Use secure url for badgesize

---

src/locale/nb.js

Norway (Norwegian Bokmål) follows ISO 8601 weeks.
So adding `yearStart: 4` should help display correct week with `weekOfYear` plugin (`.week()` function).

Update nb.js `yearStart`

---

src/locale/lt.js

Native Lithuanian here. The word is missing a dot over letter "e". Google translate screenshot to assure:

Fix Lithuanian spelling for single month

---

src/plugin/duration/index.js
test/plugin/duration.test.js

fix: when parsing duration from ISO string, set missing components to 0 instead of NaN

---

src/locale/de-at.js
src/locale/de-ch.js
test/locale/de.test.js

The locale definitions for the German regions Switzerland (de-ch) and Austria (de-at) were incomplete and wrong. This commit makes the definition complete, corrects the error regarding the setting "ordinal" for de-ch and introduces tests which verify the region specific identifiers.

Fix incomplete German locales

---

src/index.js
test/plugin/localizedFormat.test.js

Fallback to locale xx if xx-yy is provided and does not exist
Also support locales in uppercase such as en-GB

Fallback to language only locale + support uppercase locales

---

src/locale/is.js
test/locale/is.test.js

The locale file for Icelandic did not have support for relativeTime. Adding support and test coverage for the feature.

feat: Icelandic [is] support relativeTime

---

src/locale/pt-br.js
src/locale/pt.js

Based on https://github.com/iamkun/dayjs/pull/275, in this case for `pt` and `pt-br`.
Fixes https://github.com/iamkun/dayjs/issues/1696

fix(locale-pt-and-pt-br): set correct weekdays and months

---

src/locale/ku.js
test/locale/ku.test.js

Kurdish `ku` locale has it's own form of meridiem texts which are:
`AM` -> `پ.ن`
`PM` -> `د.ن`
The logic of determining which should be chosen is identical
to the main logic from the library, the only change is localized
strings for each case.
Also tests are added to the corresponding locale to ensure it
gets formatted correctly.
Closes #1724

add `meridiem` function to ku locale

---

src/index.js
src/plugin/customParseFormat/index.js
src/plugin/localeData/index.js

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.

refactor: replace deprecated String.prototype.substr()

---

src/plugin/utc/index.js
test/plugin/timezone.test.js
test/timezone.test.js

Fixes a bug in the valueOf() function after setting a utcOffset, when the the local timezone offset changes.
I added a test for it to `test/timezone.test.js`, so it should be reproducible on other people's computers as well.
Without this fix, when trying to run `npm test` in my timezone (British Summer Time - BST), there are quite a lot of off-by-one errors, e.g.
```
● DST, a time that never existed Fall Back › 2012-11-04 02:00:00
expect(received).toBe(expected) // Object.is equality
Expected value to be:
1352012400000
Received:
1352016000000
206 |       expect(d.format()).toBe('2012-11-04T02:00:00-05:00')
207 |       expect(d.utcOffset()).toBe(-300)
> 208 |       expect(d.valueOf()).toBe(1352012400000)
209 |     })
210 |   })
211 | })
at forEach (test/plugin/timezone.test.js:208:27)
at …
```

fix: utcOffset when local in DST but date is not

---

types/index.d.ts

[Here's a sandbox showing the issue and the proposed solution.](https://www.typescriptlang.org/play?#code/C4TwDgpgBAqgdgS2AZygXigIgBYHsCuATplAD5YC2Cc+wEJ5mAJgIYiYCwAUKJFAHK44AETbwkqDAHkqwADziUAGiyt2APm7de0ALLVa0DAFEAHgGMANviYQFiZarYMseIpnVA)
Fixes #1863 
Edit: [Better sandbox with relevant types](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBDAnmYcCqA7AljAKs4AZQAtp4BeOAcgBMq4AfagEXqaoFk3rFuri+AWz4BnIWICwAKFCRYCAumx4CAGQgYA5nEpVBWADYGsI4AGMNdRtVMWMV9vowBXGMD6lnUPjQCGvaz0NGAFAxGBfb0C-NyppWTIFFCUcfBR1LQAFAy9fAx1qfSMTc0sxQNsyoSwXN3L2Tyh66j9EZqCMEPbwyPaY4EkpePBEpGTMVMVKCZV0jW0mGbTgDM1s3PzF5WWSMgBuaWG5eDHUAHkwJamU2dQmACIAd2BgAGt76yeX15EP9keqAcZCN5Kc4ABFK7JabbRQPACOzkibigfzg90RyOATTRVHBgMOUgA9ES4GcDDQ4ABJQRgAzAQTATq+GBYDRHUaKADqACUzgA5ADiHF82DAzgMLOAywKZ30MAAPBcocAADQtKU+KViAB8QJJcEyUAgk …

Fix issue with `ManipulateType`

---

types/plugin/quarterOfYear.d.ts

Fixes a type error I was getting using dayjs with the quarterOfYear plugin.
[example](https://codesandbox.io/s/dayjs-types-5umhqk)

fix: add OpUnitType to quarterOfYear startOf/endOf types

---

src/locale/fr.js

This pull request fix a wrong ordinal definition for fr local.

fix: wrong ordinal for fr local

---

src/locale/ku.js

hello dayjs, in this pr add value to past property in english say ago say in kurdish say something like لەمەوپێش 
thank you.

fix: correct past property in KU (kurdish) locale

---

src/plugin/isYesterday.ts
tests/plugin/isYesterday.test.ts

feat: add plugin `isYesterday` to dayjs 2.0.
Fix changes recommended by eslint.

feat(plugin): add plugin isYesterday

---

types/plugin/objectSupport.d.ts

Close #1441.
This PR add `ConfigTypeMap` entry for `plugin/objectSupport`.
By this change, The bellow code will be treaded valid.
```typescript
x = dayjs({
year: 2010,
month: 1,
day: 12
});
dayjs.utc({
year: 2010,
month: 1,
day: 12
});
```

Add ConfigTypeMap entry for objectSupport (#1441)

---

src/locale/fr.js

In french, when writing dates, there is no ordinal for numbers over 1.
- lundi 1er août 2022 :heavy_check_mark: 
- jeudi 11 août 2022 :heavy_check_mark: 
- jeudi 11e août 2022 :x: 
In other contexts, this could be correct, but not for dates.
See for instance on this French website of the government : https://www.service-public.fr/particuliers/actualites

fix: wrong ordinal for french locale

---

src/locale/nl.js
test/plugin/advancedFormat.test.js

In dutch locale, the ordinal doesn't show properly, some letters get interpreted.
Before the fix: :x:
```javascript
dayjs().locale('nl').format('Do'); // 44e
dayjs('2022-08-23').locale('nl').format('Do'); // 230te
```
After the fix: :heavy_check_mark: 
```javascript
dayjs().locale('nl').format('Do'); // 4de
dayjs('2022-08-23').locale('nl').format('Do'); // 23ste
```

fix: ordinal for nl not working

---

src/plugin/objectSupport/index.js
test/issues/issue2027.correct-order.test.js
test/issues/issue2027.swapped-order.test.js

Using the plugins objectSupport and Duration in one file creates false result in .add and .subtract when `extend(Duration)` comes before `extend(objectSupport)` - see issue #2027.
Fixed this problem and added tests to avoid regression.

Fix objectSupport collides with Duration plugin - issue #2027

---

src/locale/en.js
src/plugin/advancedFormat/index.js

All locale files have a definition for 'ordinal' except the 'en' one. For this locale the definition of 'ordinal' is part of the 'AdvancedFormat' plugin. This is inconsistent not quite logical.
This pr solves this topic and should solve issue #1891

refactor: move declaration for english 'ordinal' to 'en' locale file

---

src/plugin/duration/index.js
test/plugin/duration.test.js

The Duration class in MomentJS contains the valueOf method (https://github.com/moment/moment/blob/develop/src/lib/duration/as.js). This method returns the duration in milliseconds. This PR adds this method also to the Dayjs Duration class.

Added valueOf method to Duration class

---

types/plugin/timezone.d.ts

LIke `dayjs()`, `dayjs.tz()` falls back to the default time internally if no parameter is passed. But the current Typescript types do not allow for this existing, expected, and correct functionality.

fix: Mark `date` parameter as optional in timezone plugin

---

src/index.js
test/display.test.js

Adds padding to the year component when formatted with `'YYYY'`, similar to how padding is handled for `'MM'` and `'DD'`.
Fixes #2230

Add missing padding to 'YYYY' format

---

test/plugin/isSameOrAfter.test.js
test/plugin/isSameOrBefore.test.js
types/index.d.ts
types/plugin/isSameOrAfter.d.ts
types/plugin/isSameOrBefore.d.ts
types/plugin/isoWeek.d.ts
types/plugin/quarterOfYear.d.ts

I don't know why this PR https://github.com/iamkun/dayjs/pull/1929 closed,
But it is quite useful to use `birthday.isBefore()` with no params in typescript.

[d.ts] first parameter date is optional in isSame(), isBefore(), isAfter()

---

src/plugin/objectSupport/index.js

This is a fix per #2277, discovered through usage with `twilio` npm package which has this same conflict.

fix: objectSupport plugin causes an error when null is passed to dayjs function (closes #2277)

---

.editorconfig
src/index.js

在高频场景下 dayjs.diff 会成为性能瓶颈, 发现在进行 `dayjs.diff(time, 'day')` 计算时会有无效的一些计算，于是优化了在进行 diff day 场景下的性能
test case
```js
const dayjs =  require('./dayjs.min.js');
let startTime = Date.now();
let endTime = Date.now() + 30 * 24 * 60 * 60 * 1000;
for(let i = 0; i < 100000; ++i) {
dayjs(startTime).diff(endTime, 'day');
}
```
before
after
执行时间由 1.35s/100000次 提升到 0.2s/100000次

dayjs.diff improve performance

---

src/plugin/objectSupport/index.js
test/plugin/objectSupport.test.js

fix: dayjs(null) throws error, not return dayjs object as invalid date #2095

fix: dayjs(null) throws error, not return dayjs object as invalid date

---

src/plugin/duration/index.js
test/plugin/duration.test.js

fix Duration add/subtract doesn't take into account how many days in a month #2336

fix: Duration add/subtract

---

types/plugin/minMax.d.ts

Currently `max` and `min` can return explicit `null` when there are no dates to compare ([see implementation](https://github.com/iamkun/dayjs/blob/dev/src/plugin/minMax/index.js#L9)).
This PR adds `null` to the return type of those functions. (I ended up with a crash on my project because I relied on the types)

fix: Add null to min and max return type

---

src/plugin/duration/index.js
test/plugin/duration.test.js

Fixes #2366 
Rounds the seconds value before formatting an ISO duration string

fix: round durations to millisecond precision for ISO string

---

src/plugin/duration/index.js
test/plugin/duration.test.js

`MILLISECONDS_A_DAY * 30` will generate wrong value for a larger diffs, it's generating wrong durations for months
it should be either `MILLISECONDS_A_DAY * 30.416666666666668` (365 / 12) or `MILLISECONDS_A_YEAR / 12`

fix: duration plugin - MILLISECONDS_A_MONTH const calculation

---

src/plugin/duration/index.js
test/plugin/duration.test.js

fix: duration plugin getter get result  0 instead of undefined

---

src/index.js
test/constructor.test.js

ref: https://github.com/moment/moment/blob/develop/src/lib/moment/constructor.js#L78
`isDayjs` should return `true` in different versions of dayjs.

fix: fix isDayjs check logic

---

src/plugin/duration/index.js
test/plugin/duration.test.js

Fixes #2376
Rounds the seconds field after adding milliseconds which covers the floating point rounding issues.

fix: sub-second precisions need to be rounded at the seconds field

---

src/locale/ar.js
test/locale/ar.test.js

Fixes https://github.com/iamkun/dayjs/issues/2416

fix(locale): add meridiem in `ar` locale

---

docs/ko/README-ko.md

Hello, I work as a Node developer in Korea. 
Many developers in Korea also use dayjs. 
While looking at the Korean README for dayjs, I noticed some translations seemed off. 
I've corrected the parts that were strangely translated.

docs: corrected incorrect Korean translations

---

src/locale/ko.js

* add '일' suffix to 'Do' format

fix: Add Korean Day of Month with ordinal

---

README.md

Hello 👋 @iamkun Thank you for sharing such a great library.
we had a problem with the doc generating for one of our packages used the packages due to `Expected corresponding JSX closing tag for <img>` at readme. also the PR has some polish in the formatting markdown

fix(docs): update image tag and formatting 

---

src/index.js

Move the initialization of the $x attribute to after the parse method so it won't be affected by other plugins
fix #2428

Fixed issue #2428

---

README.md
docs/es-es/README-es-es.md
docs/he/README-he.md
docs/ja/README-ja.md
docs/ko/README-ko.md
docs/pt-br/README-pt-br.md
docs/ru/README-ru.md
docs/si/README-si.md
docs/tr/README-tr.md
docs/zh-cn/README.zh-CN.md

CI Badge was still pointing to Travis CI, but now there are GitHub Actions
Also removes a couple of trailing whitespaces
[ci skip]

Fix CI Badge

---

src/locale/da.js

The first week of the year in Denmark is always the week containing January 4th

Update 'da' locale to match correct first week of year

---

types/plugin/minMax.d.ts

I think it's good to be clear that `null` can be returned from `min`/`max`, but TypeScript is powerful enough to be even smarter about this. This PR updates the types so that at least _obvious_ scenarios where at least one date is passed don't then require `!` or other code smells.
As with all types as they get more complex, it's easy to miss things or forget scenarios. Please let me know if I've missed anything.
I wouldn't actually consider this a "fix" so much as an _improvement on existing types_ but I don't think it's a feature and since the prior revision was marked as a fix, I'm keeping in line with that change.

Fix: Improve typing for min/max

---

src/index.js
test/timezone.test.js

fix #2248 
Just open a new PR to trigger the CI jobs. (#2399)

Fix zero offset issue when use tz with locale

---

src/index.js
src/plugin/timezone/index.js
test/plugin/timezone.test.js
test/timezone.test.js

fix https://github.com/iamkun/dayjs/issues/2248

fix: timezone plugin currect parse UTC tz

---

src/plugin/customParseFormat/index.js
test/plugin/customParseFormat.test.js

fix: customParseFormat supports Q quter / w ww weekOfYear

---

src/plugin/utc/index.js
test/plugin/utc-utcOffset.test.js

Actually `.utcOffset(0, flag)` is the same as `.utc(flag)` but `.utcOffset` with `keepLocalTime = true` didn't modify the internal date accordingly. That caused a bug described in #2501
Fixed `.utcOffset` by returning `.utc(keepLocalTime)` if passed offset is zero.
Added some tests to cover possible mismatches.

fix: .utcOffset(0, true) result and its clone are different

---

src/locale/en-au.js

The en-AU locale wasn't using ordinal at all. It should follow the same as the other English languages.

[en-AU] Use the same ordinal as moment

---

src/locale/it.js
test/locale/it.test.js

Fixes #2918
I also added tests for the it locale. However, while adding them, I noticed that "a few seconds" differs between Moment.js and Day.js:
- Moment.js → "alcuni secondi"
- Day.js → "qualche secondo"
Since both are correct but not identical, I had to split that case out from the other relative time tests.

fix: replace italian "un' ora fa" with "un'ora fa", add tests for it locale
